//
//  MainWorkerTests.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 17/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONPlaceHolderApp
import XCTest

class MainWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: MainWorker!
    static var testPosts: [Post]!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupMainWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupMainWorker() {
        sut = MainWorker()
        initPostMocks()
    }
    
    /// method that creates mocks objects of posts
    fileprivate func initPostMocks() {
        
        MainWorkerTests.testPosts = []
        
        for i in 0...9 {
            var post = Post()
            post.id = i
            post.title = "title \(i)"
            post.title = "body \(i)"
            post.user = User()
            
            MainWorkerTests.testPosts.append(post)
        }
    }
    
    class APIPostRepositorySpy: APIPostRepository {
        
        // MARK: Method call expectations
        var getPostsCalled = false
        
        override func getPosts(completion: @escaping ([Post]) -> Void) {
            getPostsCalled = true
            completion(MainWorkerTests.testPosts)
        }
    }
    
    // MARK: Tests
    
    func testGetPosts() {
        
        // Given
        let repositorySpy = APIPostRepositorySpy()
        
        // When
        var fetchedPosts = [Post]()
        
        repositorySpy.getPosts { (posts) in
            let expect = self.expectation(description: "Wait for getPosts() to return")
            fetchedPosts = posts
            expect.fulfill()
        }
        
        self.waitForExpectations(timeout: 3.0)
        
        // Then
        XCTAssertTrue(repositorySpy.getPostsCalled, "Calling getPosts() should ask the data store for a list of posts")
        XCTAssertEqual(fetchedPosts.count, MainWorkerTests.testPosts.count, "Calling getPosts() should ask the data store for a list of posts")
    }
}
