//
//  MainInteractorTests.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 17/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONPlaceHolderApp
import XCTest

class MainInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: MainInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupMainInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupMainInteractor() {
        sut = MainInteractor()
    }
    
    // MARK: Test doubles
    
    class MainPresentationLogicSpy: MainPresentationLogic {
        
        var setupViewCalled = false
        var displayLoadingCalled = false
        var presentPostsCalled = false
        var presentPostDetailsCalled = false
        
        func setupView(response: Main.SetupView.Response) {
            setupViewCalled = true
        }
        
        func displayLoading(_ show: Bool) {
            displayLoadingCalled = true
        }
        
        func presentPosts() {
            presentPostsCalled = true
        }
        
        func presentPostDetails(response: Main.DidSelectedItem.Response) {
            presentPostDetailsCalled = true
        }
    }
    
    // MARK: Tests
    
    func testDidSelectedItemAt() {
        // Given
        let spy = MainPresentationLogicSpy()
        sut.presenter = spy
        
        // When
        sut.posts = [Post(), Post()]
        sut.didSelectedItemAt(index: 0)
        
        // Then
        XCTAssertTrue(spy.presentPostDetailsCalled, "didSelectedItemAt should ask the presenter to presentPostDetailsCalled")
    }
    
    func testPostCount() {
        // Given
        let spy = MainPresentationLogicSpy()
        sut.presenter = spy
        
        // When
        sut.posts = [Post(), Post()]
        let count = sut.getPostsCount()
        
        // Then
        XCTAssertEqual(sut.posts?.count, count, "Check if count is equal to array count")
    }
    
    func testGetPostCellFor() {
        // Given
        let spy = MainPresentationLogicSpy()
        sut.presenter = spy
        
        // When
        var post = Post()
        post.id = 1
        sut.posts = [post]
        let cell = sut.getPostCellFor(index: 0)
        
        // Then
        XCTAssertEqual(cell.post?.id, 1, "Check if id is equal to 0")
    }
    
}
