//
//  MainPresenterTests.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 17/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONPlaceHolderApp
import XCTest

class MainPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: MainPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupMainPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupMainPresenter() {
        sut = MainPresenter()
    }
    
    // MARK: Test doubles
    
    class MainDisplayLogicSpy: MainDisplayLogic {
        
        var setupViewCalled = false
        var showLoadingCalled = false
        var displayPostsCalled = false
        var displayPostDetailsCalled = false
        
        func setupView(viewModel: Main.SetupView.ViewModel) {
            setupViewCalled = true
        }
        
        func showLoading(_ show: Bool) {
            showLoadingCalled = true
        }
        
        func displayPosts() {
            displayPostsCalled = true
        }
        
        func displayPostDetails(viewModel: Main.DidSelectedItem.ViewModel) {
            displayPostDetailsCalled = true
        }
    }
    
    // MARK: Tests
    
    func testSetupView() {
        // Given
        let spy = MainDisplayLogicSpy()
        sut.viewController = spy
        
        // When
        sut.setupView(response: .init())
        
        // Then
        XCTAssertTrue(spy.setupViewCalled, "setupView should ask the view controller to setupView")
    }
    
    func testPresentPosts() {
        // Given
        let spy = MainDisplayLogicSpy()
        sut.viewController = spy
        
        // When
        sut.presentPosts()
        
        // Then
        XCTAssertTrue(spy.displayPostsCalled, "presentPosts should ask the view controller to display the result")
    }
    
    func testPresentPostDetails() {
        // Given
        let spy = MainDisplayLogicSpy()
        sut.viewController = spy
        let response = Main.DidSelectedItem.Response()
        
        // When
        sut.presentPostDetails(response: response)
        
        // Then
        XCTAssertTrue(spy.displayPostDetailsCalled, "presentPostDetails should ask the view controller to display the result")
    }
}
