//
//  MainViewControllerTests.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 17/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONPlaceHolderApp
import XCTest

class MainViewControllerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: MainViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupMainViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupMainViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "MainStoryboard", bundle: bundle)
        let nv = storyboard.instantiateInitialViewController() as? UINavigationController
        sut = nv?.viewControllers.first as? MainViewController
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    class MainBusinessLogicSpy: MainBusinessLogic {
        
        var setupViewCalled = false
        var didSelectedItemAtCalled = false
        var getPostsCountCalled = false
        var getPostCellForCalled = false
        
        func setupView() {
            setupViewCalled = true
        }
        
        func didSelectedItemAt(index: Int) {
            didSelectedItemAtCalled = true
        }
        
        func getPostsCount() -> Int {
            getPostsCountCalled = true
            return 10
        }
        
        func getPostCellFor(index: Int) -> Main.Models.PostCellModel {
            getPostCellForCalled = true
            return .init()
        }
    }
    
    // MARK: Tests
    
    func testNumberOfItemsInSection() {
        // Given
        let spy = MainBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        sut.setupView(viewModel: .init())
        _ = sut.tableView(sut.postTableView, numberOfRowsInSection: 0)
        
        // Then
        XCTAssertTrue(spy.getPostsCountCalled, "numberOfItemsInSection should ask the interactor to getPostsCountCalled")
    }
    
    func testCellForItemAt() {
        // Given
        let spy = MainBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        sut.setupView(viewModel: .init())
        _ = sut.tableView(sut.postTableView, cellForRowAt: IndexPath(row: 0, section: 0))
        
        // Then
        XCTAssertTrue(spy.getPostCellForCalled, "cellForItemAt should ask the interactor to getPostCellForCalled")
    }
    
    func testDidSelectItemAt() {
        
        // Given
        let spy = MainBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        sut.setupView(viewModel: .init())
        _ = sut.tableView(sut.postTableView, didSelectRowAt: IndexPath(row: 0, section: 0))
        
        // Then
        XCTAssertTrue(spy.didSelectedItemAtCalled, "didSelectItemAt should ask the interactor to didSelectedItemAt")
    }
}
