//
//  PostDetailsInteractor.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 16/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostDetailsBusinessLogic {
    func setupView()
}

protocol PostDetailsDataStore {
    var selectedPost: Post? { get set }
}

class PostDetailsInteractor: PostDetailsBusinessLogic, PostDetailsDataStore {
    
    var presenter: PostDetailsPresentationLogic?
    var worker: PostDetailsWorker?
    var selectedPost: Post?
    
    // MARK: BusinessLogic
    
    func setupView() {
        
        let response = PostDetails.SetupView.Response(post: selectedPost)
        presenter?.setupView(response: response)
    }
}
