//
//  PostDetailsRouter.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 16/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PostDetailsRoutingLogic {
}

protocol PostDetailsDataPassing {
    var dataStore: PostDetailsDataStore? { get }
}

class PostDetailsRouter: NSObject, PostDetailsRoutingLogic, PostDetailsDataPassing {
    
    weak var viewController: PostDetailsViewController?
    var dataStore: PostDetailsDataStore?
}
