//
//  PostDetailsModels.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 16/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PostDetails {
    
    // MARK: Use cases
    
    enum SetupView {
        struct Request {
        }
        struct Response {
            var post: Post?
        }
        struct ViewModel {
            var navigationTitle: String?
            var title: String?
            var body: String?
            var userName: String?
        }
    }
    
    enum Models {
        struct CommentCellModel {
            var comment: Comment?
        }
    }
}
