//
//  PostDetailsInteractor.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 16/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostDetailsBusinessLogic {
    func setupView()
    
    // MARK: Comments
    func getCommentsCount() -> Int
    func getCommentCellFor(index: Int) -> PostDetails.Models.CommentCellModel
}

protocol PostDetailsDataStore {
    var selectedPost: Post? { get set }
}

class PostDetailsInteractor: PostDetailsBusinessLogic, PostDetailsDataStore {
    
    var presenter: PostDetailsPresentationLogic?
    var worker: PostDetailsWorker?
    var selectedPost: Post?
    var comments: [Comment]?
    
    // MARK: BusinessLogic
    
    func setupView() {
        
        worker = PostDetailsWorker()
        
        let response = PostDetails.SetupView.Response(post: selectedPost)
        presenter?.setupView(response: response)
        
        getComments()
    }
    
    /// return the comments count
    /// - Returns: count
    func getCommentsCount() -> Int {
        return comments?.count ?? 0
    }
    
    /// method returns the cellModel for current index
    /// - Parameter index: index
    /// - Returns: cell model
    func getCommentCellFor(index: Int) -> PostDetails.Models.CommentCellModel {
        
        guard let comment = comments?.getElement(index) else { return PostDetails.Models.CommentCellModel() }
        
        return PostDetails.Models.CommentCellModel(comment: comment)
    }
    
    /// method downloads the comments of selected post
    fileprivate func getComments() {
        
        guard let post = selectedPost else { return }
        
        presenter?.displayLoading(true)
        
        let deadlineTime = DispatchTime.now() + 1
        DispatchQueue.main.asyncAfter(deadline: deadlineTime) { [weak self] in
            
            self?.worker?.getComments(for: post, completion: { (comments, error) in
                
                self?.presenter?.displayLoading(false)
                self?.comments = comments
                self?.presenter?.presentComments()
            })
        }
    }
}
