//
//  PostDetailsWorker.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 16/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PostDetailsWorker {
    
    func getComments(for post: Post, completion: @escaping([Comment]?, String?) -> Void) {
        
        // LETS and VARS
        let commentsRepository = CommentRepository()
        
        // Get Comments
        commentsRepository.getComments(for: post) { (comments) in
            
            completion(comments, nil)
        }
    }
}
