//
//  PostDetailsPresenter.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 16/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostDetailsPresentationLogic {
    func setupView(response: PostDetails.SetupView.Response)
}

class PostDetailsPresenter: PostDetailsPresentationLogic {
    
    weak var viewController: PostDetailsDisplayLogic?
    
    // MARK: PresentationLogic
    
    func setupView(response: PostDetails.SetupView.Response) {
        
        let post = response.post
        let postID = String(format: "Post ID: %@", String(post?.id ?? 0))
        let userNameLabel = String(format: "%@ %@", "posts.postedBy".localized, post?.user?.username ?? "-")
        let modelView = PostDetails.SetupView.ViewModel(navigationTitle: postID, title: post?.title, body: post?.body, userName: userNameLabel)
        
        viewController?.setupView(viewModel: modelView)
    }
}
