//
//  PostDetailsInteractorTests.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 17/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONPlaceHolderApp
import XCTest

class PostDetailsInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: PostDetailsInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupPostDetailsInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupPostDetailsInteractor() {
        sut = PostDetailsInteractor()
    }
    
    // MARK: Test doubles
    
    class PostDetailsPresentationLogicSpy: PostDetailsPresentationLogic {
        
        var setupViewCalled = false
        var displayLoadingCalled = false
        var presentCommentsCalled = false
        
        func setupView(response: PostDetails.SetupView.Response) {
            setupViewCalled = true
        }
        
        func displayLoading(_ show: Bool) {
            displayLoadingCalled = true
        }
        
        func presentComments() {
            presentCommentsCalled = true
        }
    }
    
    // MARK: Tests
    
    func testSetupView() {
        // Given
        let spy = PostDetailsPresentationLogicSpy()
        sut.presenter = spy
        sut.selectedPost = Post()
        
        // When
        sut.setupView()
        
        // Then
        XCTAssertTrue(spy.setupViewCalled, "setupView should ask the presenter to setupViewCalled")
    }
    
    func testGetCommentsCount() {
        // Given
        let spy = PostDetailsPresentationLogicSpy()
        sut.presenter = spy
        
        // When
        sut.comments = [Comment(), Comment()]
        let count = sut.getCommentsCount()
        
        // Then
        XCTAssertEqual(sut.comments?.count, count, "Check if count is equal to array count")
    }
    
    func testGetCommentCellFor() {
        // Given
        let spy = PostDetailsPresentationLogicSpy()
        sut.presenter = spy
        
        // When
        var comment = Comment()
        comment.id = 1
        sut.comments = [comment]
        let cell = sut.getCommentCellFor(index: 0)
        
        // Then
        XCTAssertEqual(cell.comment?.id, 1, "Check if id is equal to 0")
    }
}
