//
//  PostDetailsViewControllerTests.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 17/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONPlaceHolderApp
import XCTest

class PostDetailsViewControllerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: PostDetailsViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupPostDetailsViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupPostDetailsViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "PostDetailsStoryboard", bundle: bundle)
        sut = storyboard.instantiateInitialViewController() as? PostDetailsViewController
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    class PostDetailsBusinessLogicSpy: PostDetailsBusinessLogic {
        
        var setupViewCalled = false
        var getCommentsCountCalled = false
        var getCommentCellForCalled = false
        
        func setupView() {
            setupViewCalled = true
        }
        
        func getCommentsCount() -> Int {
            getCommentsCountCalled = true
            return 10
        }
        
        func getCommentCellFor(index: Int) -> PostDetails.Models.CommentCellModel {
            getCommentCellForCalled = true
            return .init()
        }
    }
    
    // MARK: Tests
    
    func testSetupView() {
        // Given
        let spy = PostDetailsBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        sut.setupView(viewModel: .init())
        
        // Then
        XCTAssertTrue(spy.setupViewCalled, "viewDidLoad() should ask the interactor to setupView")
    }
    
    func testNumberOfItemsInSection() {
        // Given
        let spy = PostDetailsBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        sut.setupView(viewModel: .init())
        _ = sut.collectionView(sut.commentsCollectionView, numberOfItemsInSection: 0)
        
        // Then
        XCTAssertTrue(spy.getCommentsCountCalled, "numberOfItemsInSection should ask the interactor to getCommentsCountCalled")
    }
    
    func testCellForItemAt() {
        // Given
        let spy = PostDetailsBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        sut.setupView(viewModel: .init())
        _ = sut.collectionView(sut.commentsCollectionView, cellForItemAt: IndexPath(row: 0, section: 0))
        
        // Then
        XCTAssertTrue(spy.getCommentCellForCalled, "cellForItemAt should ask the interactor to getCommentCellForCalled")
    }
}
