//
//  PostDetailsWorkerTests.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 17/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONPlaceHolderApp
import XCTest

class PostDetailsWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: PostDetailsWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupPostDetailsWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupPostDetailsWorker() {
        sut = PostDetailsWorker()
    }
}
