//
//  PostDetailsPresenterTests.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 17/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONPlaceHolderApp
import XCTest

class PostDetailsPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: PostDetailsPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupPostDetailsPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupPostDetailsPresenter() {
        sut = PostDetailsPresenter()
    }
    
    // MARK: Test doubles
    
    class PostDetailsDisplayLogicSpy: PostDetailsDisplayLogic {
        
        var setupViewCalled = false
        var showLoadingCalled = false
        var displaycommentsCalled = false
        
        func setupView(viewModel: PostDetails.SetupView.ViewModel) {
            setupViewCalled = true
        }
        
        func showLoading(_ show: Bool) {
            showLoadingCalled = true
        }
        
        func displayComments() {
            displaycommentsCalled = true
        }
    }
    
    // MARK: Tests
    
    func testSetupView() {
        // Given
        let spy = PostDetailsDisplayLogicSpy()
        sut.viewController = spy
        
        // When
        sut.setupView(response: .init())
        
        // Then
        XCTAssertTrue(spy.setupViewCalled, "setupView should ask the view controller to setupView")
    }
    
    func testDisplayLoading() {
        // Given
        let spy = PostDetailsDisplayLogicSpy()
        sut.viewController = spy
        
        // When
        sut.displayLoading(true)
    }
    
    func testPresentComments() {
        // Given
        let spy = PostDetailsDisplayLogicSpy()
        sut.viewController = spy
        
        // When
        sut.presentComments()
        
        // Then
        XCTAssertTrue(spy.displaycommentsCalled, "presentComments should ask the view controller to displaycommentsCalled")
    }
}
