//
//  MainPresenter.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 15/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func setupView(response: Main.SetupView.Response)
    func displayLoading(_ show: Bool)
    func presentPosts()
    func presentPostDetails(response: Main.DidSelectedItem.Response)
}

class MainPresenter: MainPresentationLogic {

    weak var viewController: MainDisplayLogic?
    
    // MARK: Presentation Logic
    
    func setupView(response: Main.SetupView.Response) {
        var viewModel = Main.SetupView.ViewModel()
        viewModel.title = "posts.title".localized
        viewController?.setupView(viewModel: viewModel)
    }
    
    /// method shows loading in screen
    /// - Parameter show: flag to show loading
    func displayLoading(_ show: Bool) {
        viewController?.showLoading(show)
    }
    
    /// method shows posts in screen
    func presentPosts() {
        viewController?.displayPosts()
    }
    
    /// method navigates to details of selected post
    /// - Parameter response: response
    func presentPostDetails(response: Main.DidSelectedItem.Response) {
        // 1. create viewModel
        let viewModel = Main.DidSelectedItem.ViewModel()
        
        // 2. display data
        viewController?.displayPostDetails(viewModel: viewModel)
    }
}
