//
//  MainWorker.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 15/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainWorker {
    
    func getPosts(completion: @escaping([Post]?, String?) -> Void) {
        
        // LETS and VARS
        let repository = PostRepository()
        
        // Get Posts
        repository.getPosts { (posts) in
            print(posts)
            completion(posts, nil)
        }
    }
}
