//
//  MainRouter.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 15/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import IDIAZM

@objc protocol MainRoutingLogic {
    func routerToPostDetails(segue: UIStoryboardSegue?)
}

protocol MainDataPassing {
    var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing {
    
    weak var viewController: MainViewController?
    var dataStore: MainDataStore?
    
    // MARK: Routing
    
    func routerToPostDetails(segue: UIStoryboardSegue?) {
        let storyboard = UIStoryboard(name: Constants.Storyboard.postDetails, bundle: nil)
        
        if let segue = segue, let destinationVC = segue.destination as? PostDetailsViewController {
            var destinationDS = destinationVC.router?.dataStore
            passDataToCharacters(source: dataStore, destination: &destinationDS)
        } else if let destinationVC = storyboard.instantiateInitialViewController() as? PostDetailsViewController {
            var destinationDS = destinationVC.router?.dataStore
            passDataToCharacters(source: dataStore, destination: &destinationDS)
            navigateToComments(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    fileprivate func navigateToComments(source: MainViewController, destination: PostDetailsViewController) {
        ui {
            source.navigationController?.pushViewController(destination, animated: true)
        }
    }
    
    // MARK: Passing data
    
    fileprivate func passDataToCharacters(source: MainDataStore?, destination: inout PostDetailsDataStore?) {
        destination?.selectedPost = source?.selectedPost
    }
}
