//
//  MainModels.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 15/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main {
    
    // MARK: Use cases
    
    enum SetupView {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
            var title: String?
        }
    }
    
    enum getPosts {
        struct Request {
        }
        struct Response {
            var posts: [Post]?
        }
        struct ViewModel {
        }
    }
    
    enum Models {
        struct PostCellModel {
            var post: Post?
        }
    }
}
