//
//  MainWorker.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 15/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainWorker {
    
    func getPosts(completion: @escaping([Post]?, String?) -> Void) {
        
        // LETS and VARS
        var mPosts: [Post]?
        var mUsers: [User]?
        
        let dispatchGroup = DispatchGroup()
        
        let postRepository = PostRepository()
        let userRepository = UserRepository()
        
        // Get Posts
        dispatchGroup.enter()
        postRepository.getPosts() { posts in
            print(posts)
            mPosts = posts
            dispatchGroup.leave()
        }
        
        // Get Users
        dispatchGroup.enter()
        userRepository.getUsers() { users in
            print(users)
            mUsers = users
            dispatchGroup.leave()
        }
        
        // DispatchGroup
        dispatchGroup.notify(queue: .main) {
            
            for (index,post) in mPosts?.enumerated() ?? [].enumerated() {
                
                if let user = self.findUserBy(users: mUsers, userId: post.getUserId()) {
                    mPosts?[index].user = user
                }
            }
            
            
            var dicArray: [String] = []
            
            for tmp in mPosts ?? [] {
                
                if let res = tmp.toJSON() {
                    dicArray.append(res)
                }
            }
                                
            if let data = try? JSONSerialization.data(withJSONObject: dicArray, options: .prettyPrinted) {
                Cache.shared.savePosts(data: data, key: "posts")
            }
            
            completion(mPosts, nil)
        }
    }
    
    func selectPost(post: Post) {
        PostsManager.shared.setPostSelected(post: post)
    }
    
    fileprivate func findUserBy(users: [User]?, userId: Int) -> User? {
        return users?.first(where: {$0.id == userId})
    }
}
