//
//  MainInteractor.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 15/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func setupView()
    
    func didSelectedItemAt(index: Int)
    
    // MARK: Posts
    func getPostsCount() -> Int
    func getPostCellFor(index: Int) -> Main.Models.PostCellModel
}

protocol MainDataStore {
    var posts: [Post]? { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore {
    
    var presenter: MainPresentationLogic?
    var worker: MainWorker?
    var posts: [Post]?
    
    // MARK: Business Logic
    
    func setupView() {
        
        worker = MainWorker()
        
        let response = Main.SetupView.Response()
        presenter?.setupView(response: response)
        
        getPosts()
    }
    
    func didSelectedItemAt(index: Int) {
        guard let post = posts?.getElement(index) else { return }
        
        print(post)
    }
    
    func getPostsCount() -> Int {
        return posts?.count ?? 0
    }
    
    func getPostCellFor(index: Int) -> Main.Models.PostCellModel {
        guard let post = posts?.getElement(index) else { return Main.Models.PostCellModel() }
        
        return Main.Models.PostCellModel(post: post)
    }
    
    fileprivate func getPosts() {
        
        presenter?.displayLoading(true)
        
        let deadlineTime = DispatchTime.now() + 1
        DispatchQueue.main.asyncAfter(deadline: deadlineTime) { [weak self] in
            
            self?.worker?.getPosts(completion: { (posts, error) in
                
                self?.presenter?.displayLoading(true)
                
                self?.posts = posts
                
                self?.presenter?.displayLoading(false)
                self?.presenter?.presentPosts()
            })
        }
    }
}
