//
//  MainViewController.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 15/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import IDIAZM

protocol MainDisplayLogic: class {
    func setupView(viewModel: Main.SetupView.ViewModel)
    func showLoading(_ show: Bool)
    func presentPost()
}

class MainViewController: BaseViewController, MainDisplayLogic {
    
    var interactor: MainBusinessLogic?
    var router: (NSObjectProtocol & MainRoutingLogic & MainDataPassing)?
    
    
    // MARK: IBOutlets
    @IBOutlet weak var postTableView: IntrinsicHeightTableView!
    
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = MainInteractor()
        let presenter = MainPresenter()
        let router = MainRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        interactor?.setupView()
    }
    
    // MARK: Display Logic
    
    func setupView(viewModel: Main.SetupView.ViewModel) {
        print(#function)
        
        // NavigationController
        self.navigationItem.title = viewModel.title
        
        // TableView
        postTableView.register(PostTableViewCell.self)
        postTableView.delegate = self
        postTableView.dataSource = self
        
    }
    
    func showLoading(_ show: Bool) {
        displayLoading(show)
    }
    
    func presentPost() {
        reloadData(tableView: postTableView)
    }
}


// MARK: UITableviewDelegate and UITableViewDataSource

extension MainViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return interactor?.getPostsCount() ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        guard let cell = tableView.dequeueReusableCell(withIdentifier: PostTableViewCell.cellIdentifier) as? PostTableViewCell else {
            print("Error to cast TableViewCell to PostTableViewCell")
            return UITableViewCell()
        }
        
        guard let data = interactor?.getPostCellFor(index: indexPath.row) else {
            print("Error to get PostTableViewCell from index")
            return UITableViewCell()
        }
        
        cell.updateUI(model: data)
        
        return cell
    }
}
