//
//  MainPresenter.swift
//  JSONPlaceHolderApp
//
//  Created by Iván Díaz Molina on 15/2/21.
//  Copyright (c) 2021 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func setupView(response: Main.SetupView.Response)
    func displayLoading(_ show: Bool)
    func presentPosts()
}

class MainPresenter: MainPresentationLogic {

    weak var viewController: MainDisplayLogic?
    
    // MARK: Presentation Logic
    
    func setupView(response: Main.SetupView.Response) {
        var viewModel = Main.SetupView.ViewModel()
        viewModel.title = "posts.title".localized
        viewController?.setupView(viewModel: viewModel)
    }
    
    func displayLoading(_ show: Bool) {
        viewController?.showLoading(show)
    }
    
    func presentPosts() {
        viewController?.presentPost()
    }
    
}
